export const FETCH_USER = 'fetch_user'
export const FETCH_SURVEYS = 'fetch_surveys'
export const FETCH_MEMBERS = 'fetch_members'
export const FETCH_MEMBER = 'fetch_member'
export const DELETE_MEMBERS = 'delete_members'
